# Generated by Django 5.2.17 on 2026-08-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('tenancy', '0002_seed_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='stores',
            field=models.ManyToManyField(blank=True, related_name='store_managers', to='inventory.location'),
        ),
    ]
