# Generated by Django 5.2.17 on 2026-08-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_membership_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Forces a redirect to the password-change form on next login. Set for seed_demo accounts (shared public password); cleared automatically on change.'),
        ),
    ]
